-- GENERATED by tools/gen_stage_ddl.py — 직접 수정 금지 (재생성으로만 갱신)
-- stage 변형: ON CLUSTER 제거 + Replicated→MergeTree (홈랩 CHI는 ZK 없음)
-- 원본: assets/user-org/ddl/company/accounts.sql

-- =============================================================
-- user-org 모듈 GRANT 추가분 (스펙 v1.12 §7.2 계정·GRANT 경계)
-- 실행 주체: admin 수동. 계정은 동료 소유의 기존 운영계정 `mart`를 공유
--   한다(전용 계정 폐지, 계정 공유 합의 2026-07-14 — 이슈 #1). 이 파일은
--   CREATE USER를 하지 않는다.
--
-- 쓰기 주체 확정 (§6.1 1단계 + §8.3 문구의 해소): dim_token_user_org의
--   INSERT(이력 append)·파기/가명화(ALTER DELETE/UPDATE)는 전부 admin
--   수동 실행 — 전용 쓰기 계정을 두지 않는다. 근거: 1단계 투입은
--   "사내 절차로만 투입·리뷰"(§6.1)이고 빈도가 낮으며, 개인정보 테이블의
--   쓰기 권한을 상시 계정에 부여하지 않는 것이 최소 권한이다.
--   2단계 sync CronJob 도입 시(§9-2) 전용 계정을 그때 신설한다.
-- =============================================================

-- mart(공유 계정) — STEP 1 이력 조인 읽기 (_dist만 — _local 우회 차단, dim_token_service 선례) (mart accounts.sql 헤더의 Plan 4 귀속 명시분)
GRANT SELECT ON gpu_data.dim_token_user_org_dist TO mart;