-- =============================================================
-- GENERATED by tools/gen_verify_ddl.py — 직접 수정 금지
-- source: collectors/token-usage/ddl/company/accounts.sql
-- params: --fact=token_verify_fact --dim=token_verify_dim --mart=token_verify_mart --account=token_verify
-- =============================================================

-- -------------------------------------------------------------
-- 1단계 격리 검증 전용 — DB 3종 + 전용 계정 생성.
-- 철수 시: DROP DATABASE IF EXISTS <db> ON CLUSTER 'gpu-monitoring' 3종 +
--   DROP USER IF EXISTS token_verify ON CLUSTER 'gpu-monitoring'
--   (docs/operations/company-verify.md 철수 절차 참조).
-- -------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS token_verify_fact ON CLUSTER 'gpu-monitoring';
CREATE DATABASE IF NOT EXISTS token_verify_dim ON CLUSTER 'gpu-monitoring';
CREATE DATABASE IF NOT EXISTS token_verify_mart ON CLUSTER 'gpu-monitoring';
CREATE USER IF NOT EXISTS token_verify ON CLUSTER 'gpu-monitoring' IDENTIFIED WITH sha256_password BY 'CHANGE_ME_VERIFY';

-- =============================================================
-- 공유 계정 mart 앞 GRANT (스펙 v1.12 §7.2 계정·GRANT 경계)
-- 실행 주체: admin 수동 (install.sh 자동 적용 대상 아님 — §7.2)
--
-- 계정 공유 합의 (2026-07-14, 이슈 #1 — 사용자·클러스터 소유자):
--  - 전용 계정 3종(token_collector/token_mart/token_dashboard_reader)을
--    폐지하고, 동료의 기존 운영계정 `mart`를 공유한다. 계정 생성·비밀번호
--    관리는 동료 소유 — 이 파일은 더 이상 CREATE USER를 하지 않는다.
--  - GRANT는 여전히 우리 몫만 **자기 테이블에 테이블 레벨**로 명시 부여한다
--    (동료 계정 `mart`가 이미 DB 레벨 광역 GRANT를 가지고 있을 수 있으나,
--    그것과 무관하게 우리 쪽 최소 권한 계약을 이 파일에 문서화해 둔다 —
--    향후 GRANT가 좁혀지거나 계정이 다시 분리되어도 우리 요구사항이
--    남아있도록 하기 위함)
--  - 신규 테이블 추가 시 GRANT 추가는 migrate_add_*.sql 절차의 일부
--
-- 기존 token_* 계정이 생성돼 있으면:
--   DROP USER IF EXISTS token_collector, token_mart, token_dashboard_reader
--   ON CLUSTER 'gpu-monitoring'; -- 소유자와 협의 후
-- =============================================================

-- fact DB 생성은 admin — §7.2 DDL 실행 주체 분리
CREATE DATABASE IF NOT EXISTS token_verify_fact
ON CLUSTER 'gpu-monitoring';

-- 1) 수집기 몫 GRANT (구 token_collector) -----------------------
-- 수집 원본: 존재 확인 SELECT(§4.0 no-op 스킵) + INSERT + 멱등 DELETE(local만)
GRANT SELECT, INSERT ON token_verify_fact.raw_token_usage_1d_dist          TO token_verify ON CLUSTER 'gpu-monitoring';
GRANT SELECT, INSERT ON token_verify_fact.raw_token_usage_1d_local         TO token_verify ON CLUSTER 'gpu-monitoring';
GRANT ALTER DELETE   ON token_verify_fact.raw_token_usage_1d_local         TO token_verify ON CLUSTER 'gpu-monitoring';
GRANT SELECT, INSERT ON token_verify_fact.raw_token_usage_summary_1d_dist  TO token_verify ON CLUSTER 'gpu-monitoring';
GRANT SELECT, INSERT ON token_verify_fact.raw_token_usage_summary_1d_local TO token_verify ON CLUSTER 'gpu-monitoring';
GRANT ALTER DELETE   ON token_verify_fact.raw_token_usage_summary_1d_local TO token_verify ON CLUSTER 'gpu-monitoring';
-- 교체 감사(append-only): INSERT만 — DELETE 권한 없음 (감사 불변성)
GRANT SELECT, INSERT ON token_verify_fact.collect_audit_1d_dist            TO token_verify ON CLUSTER 'gpu-monitoring';
GRANT SELECT, INSERT ON token_verify_fact.collect_audit_1d_local           TO token_verify ON CLUSTER 'gpu-monitoring';
-- 서비스 레지스트리: 자기 source_type 범위 교체 (§5.9 계약 6조)
GRANT SELECT, INSERT ON token_verify_dim.dim_token_service_dist                   TO token_verify ON CLUSTER 'gpu-monitoring';
GRANT SELECT, INSERT ON token_verify_dim.dim_token_service_local                  TO token_verify ON CLUSTER 'gpu-monitoring';
GRANT ALTER DELETE   ON token_verify_dim.dim_token_service_local                  TO token_verify ON CLUSTER 'gpu-monitoring';
-- mutations_sync=2 방식이므로 system.mutations 권한 불요 (§7.2)

-- 2) mart 배치 몫 GRANT (구 token_mart) --------------------------
-- (mart·view 테이블 GRANT는 Plan 3 DDL에서 추가 — 여기는 읽기 원천만)
GRANT SELECT ON token_verify_fact.raw_token_usage_1d_dist         TO token_verify ON CLUSTER 'gpu-monitoring';
GRANT SELECT ON token_verify_fact.raw_token_usage_summary_1d_dist TO token_verify ON CLUSTER 'gpu-monitoring';
GRANT SELECT ON token_verify_fact.collect_audit_1d_dist           TO token_verify ON CLUSTER 'gpu-monitoring';
GRANT SELECT ON token_verify_dim.dim_token_service_dist                  TO token_verify ON CLUSTER 'gpu-monitoring';
-- clusterAllReplicas 폴링(wait_for_mutations) + GLOBAL JOIN에 필요 (§7.2, 동료 mart 관례와 동일)
GRANT SELECT ON system.mutations TO token_verify ON CLUSTER 'gpu-monitoring';
GRANT CREATE TEMPORARY TABLE ON *.* TO token_verify ON CLUSTER 'gpu-monitoring';
