-- =============================================================
-- GENERATED by tools/gen_verify_ddl.py — 직접 수정 금지
-- source: assets/user-org/ddl/company/accounts.sql
-- params: --fact=token_verify_fact --dim=token_verify_dim --mart=token_verify_mart --account=token_verify
-- =============================================================

-- -------------------------------------------------------------
-- 1단계 격리 검증 전용 — DB 3종 + 전용 계정 생성.
-- 철수 시: DROP DATABASE IF EXISTS <db> ON CLUSTER 'gpu-monitoring' 3종 +
--   DROP USER IF EXISTS token_verify ON CLUSTER 'gpu-monitoring'
--   (docs/operations/company-verify.md 철수 절차 참조).
-- -------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS token_verify_fact ON CLUSTER 'gpu-monitoring';
CREATE DATABASE IF NOT EXISTS token_verify_dim ON CLUSTER 'gpu-monitoring';
CREATE DATABASE IF NOT EXISTS token_verify_mart ON CLUSTER 'gpu-monitoring';
CREATE USER IF NOT EXISTS token_verify ON CLUSTER 'gpu-monitoring' IDENTIFIED WITH sha256_password BY 'CHANGE_ME_VERIFY';

-- =============================================================
-- user-org 모듈 GRANT 추가분 (스펙 v1.12 §7.2 계정·GRANT 경계)
-- 실행 주체: admin 수동. 계정은 동료 소유의 기존 운영계정 `mart`를 공유
--   한다(전용 계정 폐지, 계정 공유 합의 2026-07-14 — 이슈 #1). 이 파일은
--   CREATE USER를 하지 않는다.
--
-- 쓰기 주체 확정 (§6.1 1단계 + §8.3 문구의 해소): dim_token_user_org의
--   INSERT(이력 append)·파기/가명화(ALTER DELETE/UPDATE)는 전부 admin
--   수동 실행 — 전용 쓰기 계정을 두지 않는다. 근거: 1단계 투입은
--   "사내 절차로만 투입·리뷰"(§6.1)이고 빈도가 낮으며, 개인정보 테이블의
--   쓰기 권한을 상시 계정에 부여하지 않는 것이 최소 권한이다.
--   2단계 sync CronJob 도입 시(§9-2) 전용 계정을 그때 신설한다.
-- =============================================================

-- mart(공유 계정) — STEP 1 이력 조인 읽기 (_dist만 — _local 우회 차단, dim_token_service 선례) (mart accounts.sql 헤더의 Plan 4 귀속 명시분)
GRANT ON CLUSTER 'gpu-monitoring' SELECT ON token_verify_dim.dim_token_user_org_dist TO token_verify;