-- GENERATED by tools/gen_stage_ddl.py — 직접 수정 금지 (재생성으로만 갱신)
-- stage 변형: ON CLUSTER 제거 + Replicated→MergeTree (홈랩 CHI는 ZK 없음)
-- 원본: mart/token-metrics/ddl/company/accounts.sql

-- =============================================================
-- mart/token-metrics GRANT 추가분 (설계 2026-08-31 §4.2 GRANT 표 · 마스터 v1.12 §7.2 계정·GRANT 경계)
-- 실행 주체: admin 수동 (install.sh 자동 적용 대상 아님 — §7.2)
-- 계정: 공유 운영계정 mart (계정 생성·비밀번호는 동료 소유 — 이 파일은 사용자를 만들지 않는다)
-- 원칙: 자기 테이블에 테이블 레벨 GRANT만(DB 레벨 금지); INSERT는 _dist 경유만, _local에는 멱등 DELETE용 ALTER DELETE만.
--   정규형 `GRANT ON CLUSTER ... <priv> ON <table> TO <user>`. 이미 있는 권한은 no-op.
-- 기존 mart/token-usage/ddl/company/accounts.sql 무수정 — 신규 테이블 몫 + 읽기 계약 몫만 여기에.
-- =============================================================

-- 1) mart-metrics 자기 테이블 (M1·M3·M4·M2) ----------------------------------

GRANT SELECT, INSERT ON mart.agg_token_model_cost_1d_dist   TO mart;
GRANT ALTER DELETE   ON mart.agg_token_model_cost_1d_local  TO mart;
GRANT SELECT, INSERT ON mart.token_metrics_check_1d_dist    TO mart;
GRANT ALTER DELETE   ON mart.token_metrics_check_1d_local   TO mart;
GRANT SELECT, INSERT ON mart.agg_token_model_share_1d_dist  TO mart;
GRANT ALTER DELETE   ON mart.agg_token_model_share_1d_local TO mart;
GRANT SELECT, INSERT ON mart.agg_token_gpu_group_1d_dist    TO mart;
GRANT ALTER DELETE   ON mart.agg_token_gpu_group_1d_local   TO mart;

-- 2) 기준정보 읽기 (Layer C 3 + alias + 메트릭 레지스트리 + 토큰 레지스트리) ------
--    dim 4종 SELECT는 assets/model-catalog/ddl/company/accounts_metrics.sql과 중복 — 이미 있으면 no-op

GRANT SELECT ON gpu_data.dim_token_model_alias_dist     TO mart;
GRANT SELECT ON gpu_data.dim_token_gpu_tco_dist         TO mart;
GRANT SELECT ON gpu_data.dim_token_gpu_allocation_dist  TO mart;
GRANT SELECT ON gpu_data.dim_token_vendor_price_dist    TO mart;
GRANT SELECT ON gpu_data.dim_token_metrics_service_dist TO mart;
GRANT SELECT ON gpu_data.dim_token_service_dist         TO mart;

-- 3) 소스 읽기 — 메트릭 fact 3 + 토큰 mart 읽기 계약 2 (§6.1: 3테이블/13컬럼) -----

GRANT SELECT ON fact.raw_token_metrics_gpu_1d_dist     TO mart;
GRANT SELECT ON fact.raw_token_metrics_serving_1d_dist TO mart;
GRANT SELECT ON fact.raw_token_metrics_summary_1d_dist TO mart;
GRANT SELECT ON mart.token_usage_1d_dist               TO mart;
GRANT SELECT ON mart.agg_token_service_1d_dist         TO mart;

-- 4) 배치 실행 권한 — GLOBAL JOIN 임시 테이블·뮤테이션 폴링 (기존 collectors/token-usage/ddl/company/accounts.sql 49-50행과 동일 권한 — no-op if present)

GRANT CREATE TEMPORARY TABLE ON *.* TO mart;
GRANT SELECT ON system.mutations TO mart;
