-- GENERATED by tools/gen_stage_ddl.py — 직접 수정 금지 (재생성으로만 갱신)
-- stage 변형: ON CLUSTER 제거 + Replicated→MergeTree (홈랩 CHI는 ZK 없음)
-- 원본: assets/model-catalog/ddl/company/accounts.sql

-- =============================================================
-- model-catalog 모듈 GRANT 추가분 (스펙 v1.12 §7.2 계정·GRANT 경계)
-- 실행 주체: admin 수동. 계정은 동료 소유의 기존 운영계정 `mart`를 공유
--   한다(전용 계정 폐지, 계정 공유 합의 2026-07-14 — 이슈 #1). 이 파일은
--   CREATE USER를 하지 않는다.
-- 쓰기 주체: 시드/단가 갱신 SQL은 admin 수동 (§6.2 — 전용 계정 없음).
-- =============================================================

-- mart(공유 계정) — STEP 1 단가 조인 읽기 (_dist만 — _local 우회 차단) (mart accounts.sql 헤더의 Plan 4 귀속 명시분)
GRANT SELECT ON gpu_data.dim_token_model_dist  TO mart;