-- GENERATED by tools/gen_stage_ddl.py — 직접 수정 금지 (재생성으로만 갱신)
-- stage 변형: ON CLUSTER 제거 + Replicated→MergeTree (홈랩 CHI는 ZK 없음)
-- 원본: mart/token-usage/ddl/company/accounts.sql

-- stage 한정: mart DB 생성 (홈랩엔 동료 스택 부재 — company에선 §9-18 공유 DB)
CREATE DATABASE IF NOT EXISTS mart;

-- =============================================================
-- mart 모듈 GRANT 추가분 (스펙 v1.12 §7.2 계정·GRANT 경계)
-- 실행 주체: admin 수동 (install.sh 자동 적용 대상 아님 — §7.2)
--
-- 계정 공유 합의 (2026-07-14, 이슈 #1 — 사용자·클러스터 소유자): 전용
-- token_mart/token_dashboard_reader 계정을 폐지하고 동료의 기존 운영계정
-- `mart`를 공유한다. 계정 생성·비밀번호 관리는 동료 소유 — 이 파일은
-- CREATE USER를 하지 않는다. 이 파일은 Plan 3 신규 테이블에 대한 GRANT만
-- 추가한다 (migrate_add_* 관행의 mart 초기분).
-- 원칙 (§7.2):
--  - 자기 테이블에 테이블 레벨 GRANT만 — DB 레벨 금지 (동료 계정 `mart`가
--    이미 DB 레벨 광역 GRANT를 가지고 있을 수 있으나, 우리 몫은 명시적으로
--    테이블 레벨로 문서화한다)
--  - INSERT는 _dist 경유만 (fact와의 co-location 라우팅 일관성 — §4.0);
--    _local에는 멱등 DELETE용 ALTER DELETE만
--  - GRANT 문은 정규형 `GRANT ON CLUSTER ... <priv> ON <table> TO <user>`
-- 주의: STEP 1이 조인하는 gpu_data.dim_token_user_org / dim_token_model의 SELECT GRANT는
--   해당 테이블을 만드는 assets DDL(Plan 4)의 accounts에 귀속 —
--   mart 가동 전 Plan 4 적용이 전제다 (ddl/README.md 적용 순서 참조).
--
-- 기존 token_mart/token_dashboard_reader 계정이 생성돼 있으면:
--   DROP USER IF EXISTS token_mart, token_dashboard_reader
--  ; -- 소유자와 협의 후
-- =============================================================

-- 1) mart 자기 테이블 (STEP 1) — 구 token_mart 몫 ----------------

GRANT SELECT, INSERT ON mart.token_usage_1d_dist        TO mart;
GRANT ALTER DELETE   ON mart.token_usage_1d_local       TO mart;
GRANT SELECT, INSERT ON mart.agg_token_service_1d_dist  TO mart;
GRANT ALTER DELETE   ON mart.agg_token_service_1d_local TO mart;
GRANT SELECT, INSERT ON mart.agg_token_org_1d_dist      TO mart;
GRANT ALTER DELETE   ON mart.agg_token_org_1d_local     TO mart;
GRANT SELECT, INSERT ON mart.agg_token_model_1d_dist    TO mart;
GRANT ALTER DELETE   ON mart.agg_token_model_1d_local   TO mart;

-- 2) view 테이블 (STEP 2) — 구 token_mart 몫 ----------------------

GRANT SELECT, INSERT ON gpu_data.view_token_usage_1d_dist          TO mart;
GRANT ALTER DELETE   ON gpu_data.view_token_usage_1d_local         TO mart;
GRANT SELECT, INSERT ON gpu_data.view_token_usage_service_1d_dist  TO mart;
GRANT ALTER DELETE   ON gpu_data.view_token_usage_service_1d_local TO mart;
GRANT SELECT, INSERT ON gpu_data.view_token_usage_org_1d_dist      TO mart;
GRANT ALTER DELETE   ON gpu_data.view_token_usage_org_1d_local     TO mart;
GRANT SELECT, INSERT ON gpu_data.view_token_usage_model_1d_dist    TO mart;
GRANT ALTER DELETE   ON gpu_data.view_token_usage_model_1d_local   TO mart;

-- 3) 대시보드 읽기 — 계정 공유 결정으로 대체 ----------------------
--    대시보드도 mart 계정 사용(계정 공유 결정, 2026-07-14) — 위 1)/2)의
--    GRANT가 이미 mart 계정에 view 테이블 SELECT를 포함하므로, 구
--    token_dashboard_reader용 read-only GRANT 문은 더 이상 필요하지
--    않다(중복이 되므로 별도로 추가하지 않는다).
--    잔여 리스크(명시): 쓰기 권한 계정의 대시보드 사용·실명 dim 접근은
--    §9-1/§9-3 협의로 이관 — 구 token_dashboard_reader가 강제하던
--    "view만 SELECT, fact·mart·dim 직접 조회 차단" 경계는 계정 분리로는
--    더 이상 성립하지 않으며, mart 계정은 실명 dim(gpu_data.dim_token_user_org)에도
--    접근 가능하다. per-user 노출 grain·ROW POLICY 필요 여부는 별도 확정.

-- 4) mart 서버측 설정 — 이 파일에서 변경하지 않음 -----------------
--    insert_deduplicate=0은 클라이언트 설정(CHGate)으로만 적용 — 공유
--    계정 서버측 변경은 소유자 판단(이슈 #1).
--    (구: `ALTER USER token_mart SETTINGS insert_deduplicate = 0;` — 제거됨,
--    사유: 공유 계정 `mart`에 대한 서버측 SETTINGS 변경은 이 파이프라인이
--    전역으로 좌우할 수 없다 — 클라이언트 측 insert_deduplicate=0
--    (app/ch.py의 insert_select)로 계약을 유지한다)
