-- =============================================================
-- GENERATED by tools/gen_verify_ddl.py — 직접 수정 금지
-- source: assets/model-catalog/ddl/company/accounts.sql
-- params: --fact=token_verify_fact --dim=token_verify_dim --mart=token_verify_mart --account=token_verify
-- =============================================================

-- -------------------------------------------------------------
-- 1단계 격리 검증 전용 — DB 3종 + 전용 계정 생성.
-- 철수 시: DROP DATABASE IF EXISTS <db> ON CLUSTER 'gpu-monitoring' 3종 +
--   DROP USER IF EXISTS token_verify ON CLUSTER 'gpu-monitoring'
--   (docs/operations/company-verify.md 철수 절차 참조).
-- -------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS token_verify_fact ON CLUSTER 'gpu-monitoring';
CREATE DATABASE IF NOT EXISTS token_verify_dim ON CLUSTER 'gpu-monitoring';
CREATE DATABASE IF NOT EXISTS token_verify_mart ON CLUSTER 'gpu-monitoring';
CREATE USER IF NOT EXISTS token_verify ON CLUSTER 'gpu-monitoring' IDENTIFIED WITH sha256_password BY 'CHANGE_ME_VERIFY';

-- =============================================================
-- model-catalog 모듈 GRANT 추가분 (스펙 v1.12 §7.2 계정·GRANT 경계)
-- 실행 주체: admin 수동. 계정은 동료 소유의 기존 운영계정 `mart`를 공유
--   한다(전용 계정 폐지, 계정 공유 합의 2026-07-14 — 이슈 #1). 이 파일은
--   CREATE USER를 하지 않는다.
-- 쓰기 주체: 시드/단가 갱신 SQL은 admin 수동 (§6.2 — 전용 계정 없음).
-- =============================================================

-- mart(공유 계정) — STEP 1 단가 조인 읽기 (_dist만 — _local 우회 차단) (mart accounts.sql 헤더의 Plan 4 귀속 명시분)
GRANT ON CLUSTER 'gpu-monitoring' SELECT ON token_verify_dim.dim_token_model_dist  TO token_verify;