-- =============================================================
-- GENERATED by tools/gen_verify_ddl.py — 직접 수정 금지
-- source: assets/model-catalog/ddl/company/seed_dim_token_gpu_allocation.sql
-- params: --fact=token_verify_fact --dim=token_verify_dim --mart=token_verify_mart --account=token_verify
-- =============================================================

-- =============================================================
-- token_verify_dim.dim_token_gpu_allocation 시드 (설계 2026-08-31 §4.2 — dim_holiday 3요소 패턴)
-- (a) 출처·기준일: 플레이스홀더만 — (service_group='unknown', gpu_type='unknown', NULL, 2026-01-01).
--     실값(그룹별 GPU 할당 장수)은 assets/model-catalog/csv_to_layer_c_dim_insert.py --table gpu_allocation
--     생성 SQL(gitignore)을 admin이 append 적용. M2는 gpu_type='unknown' 행을 무시(no_allocation으로만 노출).
-- (b) NOT IN 멱등 가드 — 재실행 안전.
-- (c) 말미 검증 SELECT — 결과가 비어야 정상.
-- 실행 주체: admin 수동. mart는 SELECT만. stage 합성값은 fixtures/stage_seed_dim_token_gpu_allocation.sql.
-- =============================================================

INSERT INTO token_verify_dim.dim_token_gpu_allocation_dist
    (service_group, gpu_type, effective_from, allocated_gpu_count, source, note)
SELECT *
FROM (
    SELECT 'unknown' AS service_group, 'unknown' AS gpu_type, toDate('2026-01-01') AS effective_from,
           CAST(NULL AS Nullable(Float64)) AS allocated_gpu_count,
           'seed' AS source, '계약 표준 값 — 할당표 미확정 플레이스홀더' AS note
)
WHERE (service_group, gpu_type, effective_from) NOT IN (
    SELECT service_group, gpu_type, effective_from FROM token_verify_dim.dim_token_gpu_allocation_dist
)
SETTINGS insert_distributed_sync = 1;

-- 검증: 결과가 비어야 정상 ------------------------------------------------
-- 1) (service_group, gpu_type, effective_from) 키 중복 없음
SELECT 'dup_key' AS check_name, concat(service_group, '/', gpu_type) AS key, effective_from, count() AS cnt
FROM token_verify_dim.dim_token_gpu_allocation_dist
GROUP BY service_group, gpu_type, effective_from
HAVING count() > 1

UNION ALL

-- 2) unknown 플레이스홀더 행 존재 + gpu_type='unknown' 행은 전부 NULL (값이 들어가면 M2 무시 대상에 값이 숨는 것)
SELECT 'unknown_row_state', 'unknown', toDate('2026-01-01'), countIf(allocated_gpu_count IS NOT NULL)
FROM token_verify_dim.dim_token_gpu_allocation_dist
WHERE gpu_type = 'unknown'
HAVING count() = 0 OR countIf(allocated_gpu_count IS NOT NULL) > 0

UNION ALL

-- 3) 음수 할당 금지 (철회는 0 행)
SELECT 'negative_count', concat(service_group, '/', gpu_type), effective_from, toUInt64(1)
FROM token_verify_dim.dim_token_gpu_allocation_dist
WHERE allocated_gpu_count < 0;
