-- =============================================================
-- GENERATED by tools/gen_verify_ddl.py — 직접 수정 금지
-- source: assets/model-catalog/ddl/company/seed_dim_token_model.sql
-- params: --fact=token_verify_fact --dim=token_verify_dim --mart=token_verify_mart --account=token_verify
-- =============================================================

-- =============================================================
-- token_verify_dim.dim_token_model 시드 (§6.2 — dim_holiday 3요소 패턴)
-- (a) 출처·기준일: Anthropic 공표 단가 2026-01 기준 (USD per MTok).
--     실계약가·통화 확정은 §9-5 미결 — 확정 시 새 effective_from 행 추가.
-- (b) NOT IN 멱등 가드 — 재실행 안전.
-- (c) 말미 검증 SELECT — 결과가 비어야 정상.
-- 실행 주체: admin 수동 (§7.2 DDL 실행 주체 분리).
-- 단가 변경 절차: 기존 행 수정 금지 — 새 effective_from 행을 이 파일에
--   append 후 재실행 (NOT IN 가드가 기존 행을 건너뜀). 소급 정정은
--   이력 정정 후 해당 기간 mart rerun (§4.3, docs/operations/rerun.md).
-- =============================================================

INSERT INTO token_verify_dim.dim_token_model_dist
    (model, effective_from, provider, serving_type, input_usd_per_mtok,
     cache_read_usd_per_mtok, cache_creation_usd_per_mtok, output_usd_per_mtok,
     currency, note)
SELECT *
FROM (
    SELECT 'claude-opus-4-8'  AS model, toDate('2026-01-01') AS effective_from,
           'anthropic' AS provider, 'external' AS serving_type,
           toNullable(5.0) AS input_usd_per_mtok, toNullable(0.5) AS cache_read_usd_per_mtok,
           toNullable(6.25) AS cache_creation_usd_per_mtok, toNullable(25.0) AS output_usd_per_mtok,
           'USD' AS currency, '공표 단가 2026-01' AS note
    UNION ALL
    SELECT 'claude-sonnet-5', toDate('2026-01-01'), 'anthropic', 'external',
           toNullable(3.0), toNullable(0.3), toNullable(3.75), toNullable(15.0),
           'USD', '공표 단가 2026-01 — 인트로가 미반영(정가 기준)'
    UNION ALL
    SELECT 'claude-haiku-4-5', toDate('2026-01-01'), 'anthropic', 'external',
           toNullable(1.0), toNullable(0.1), toNullable(1.25), toNullable(5.0),
           'USD', '공표 단가 2026-01'
    -- 계약 표준값 unknown: 전 단가 NULL — "미등록 WARN"이 unknown으로 상시
    -- 발화해 경보가 무력화되는 것을 방지 (§4.2 리뷰 #15)
    UNION ALL
    SELECT 'unknown', toDate('2026-01-01'), '', 'external',
           NULL, NULL, NULL, NULL,
           'USD', '계약 표준 값 — 단가 산정 불가'
)
WHERE (model, effective_from) NOT IN (
    SELECT model, effective_from FROM token_verify_dim.dim_token_model_dist
)
-- 동기 분산 삽입 — 같은 파일의 멱등 가드·말미 검증이 미플러시 행을 놓치지 않게 (§7.2)
-- (company 2레플리카에서 즉시 재실행할 경우 복제 지연 잔여 위험 — 재실행은 수 분 간격 권장.
--  admin 세션에서 insert_quorum=2를 추가하면 지연까지 커버 — stage 1레플리카에선 금지)
SETTINGS insert_distributed_sync = 1;

-- 검증: 결과가 비어야 정상 ------------------------------------------------
-- 1) (model, effective_from) 키 중복 없음
SELECT 'dup_key' AS check_name, model, effective_from, count() AS cnt
FROM token_verify_dim.dim_token_model_dist
GROUP BY model, effective_from
HAVING count() > 1

UNION ALL

-- 2) unknown 행 존재 + 전 단가 NULL (행 부재 또는 단가 오염 시 위반 행 노출)
SELECT 'unknown_row_state', 'unknown', toDate('2026-01-01'),
       countIf(input_usd_per_mtok IS NULL AND cache_read_usd_per_mtok IS NULL
               AND cache_creation_usd_per_mtok IS NULL AND output_usd_per_mtok IS NULL)
FROM token_verify_dim.dim_token_model_dist
WHERE model = 'unknown'
HAVING countIf(input_usd_per_mtok IS NULL AND cache_read_usd_per_mtok IS NULL
               AND cache_creation_usd_per_mtok IS NULL AND output_usd_per_mtok IS NULL) != 1;
