#!/usr/bin/env python3
"""company 2단계 검증 — 1단계(격리 DB) verify DDL 생성기.

배경 (docs/operations/company-verify.md 참조): company 반입 전 격리 검증 단계에서는
production DB(fact/gpu_data/mart)를 오염시키지 않기 위해, 같은 물리 클러스터
('gpu-monitoring') 위에 이름만 다른 DB 3종(기본: token_verify_fact/token_verify_dim/
token_verify_mart)과 전용 계정(기본: token_verify)을 두고 그 안에서 동일한 스키마를
검증한다.

이 스크립트는 각 모듈의 `ddl/company/*.sql`을 읽어 구조 토큰(DB 한정자, ZK 복제 경로,
Distributed 엔진 인자, GRANT 대상 계정)만 치환한 `ddl/company-verify/*.sql` 미러를
생성한다. COMMENT 산문(주석 텍스트) 안의 원 DB명 언급은 치환되어도/안 되어도 무관 —
검증 대상은 구조 토큰뿐이다.

**치환 규칙**:
  ① 한정자 `fact.` / `gpu_data.` / `mart.` → verify DB명 + `.`
  ② ZK 복제 경로 `/clickhouse/tables/{shard}/<db>/` — 누락 시 기존 Replicated 테이블과
     복제 상태가 꼬이는 최악 케이스이므로, 생성 후 원 DB명 잔존 0을 별도로 단정한다.
  ③ `Distributed('gpu-monitoring', '<db>', ...)`의 둘째 인자
  ④ GRANT의 `TO mart` → `TO <verify 계정>`
  ⑤ `accounts.sql`류(파일명이 정확히 accounts.sql)에는 파일 머리에
     `CREATE DATABASE IF NOT EXISTS <verify DB> ON CLUSTER 'gpu-monitoring';` × 3 +
     `CREATE USER IF NOT EXISTS <verify 계정> ON CLUSTER 'gpu-monitoring' IDENTIFIED
     WITH sha256_password BY 'CHANGE_ME_VERIFY';` 블록을 프리펜드한다(1단계 전용 —
     철수 시 DROP). collectors accounts.sql의 기존 `CREATE DATABASE IF NOT EXISTS fact`
     문도 verify명으로 치환된다(별도 규칙 아님 — bare CREATE DATABASE 문 치환).

사용법:
  python3 tools/gen_verify_ddl.py                      # 기본값으로 생성(파일 기록)
  python3 tools/gen_verify_ddl.py --check               # 커밋본과 diff, 불일치 시 exit 1
  python3 tools/gen_verify_ddl.py --fact my_fact --dim my_dim --mart my_mart --account my_user

생성 파일은 커밋 대상이다(리뷰 가능성) — `--check`는 CI 드리프트 가드로,
`ddl/company/*.sql` 원본이 바뀌었는데 `ddl/company-verify/*.sql` 미러 재생성을
잊은 경우를 잡는다.
"""
import argparse
import difflib
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]

DEFAULT_FACT = "token_verify_fact"
DEFAULT_DIM = "token_verify_dim"
DEFAULT_MART = "token_verify_mart"
DEFAULT_ACCOUNT = "token_verify"

# 원 DB명(치환 대상) — 순서 무관, alternation에 그대로 사용
ORIGINAL_DBS = ("fact", "gpu_data", "mart")

GENERATED_BANNER = "GENERATED by tools/gen_verify_ddl.py — 직접 수정 금지"

# 모듈별 소스 위치. collectors/mart는 파일 목록 고정, assets 2종은 ddl/company/*.sql 전체.
MODULES = [
    {
        "label": "collectors/token-usage",
        "src_dir": REPO_ROOT / "collectors/token-usage/ddl/company",
        "out_dir": REPO_ROOT / "collectors/token-usage/ddl/company-verify",
        "files": ["raw_token_usage.sql", "dim_token_service.sql", "accounts.sql"],
    },
    {
        "label": "mart/token-usage",
        "src_dir": REPO_ROOT / "mart/token-usage/ddl/company",
        "out_dir": REPO_ROOT / "mart/token-usage/ddl/company-verify",
        "files": ["mart_tables.sql", "view_token_usage.sql", "accounts.sql"],
    },
    {
        "label": "assets/user-org",
        "src_dir": REPO_ROOT / "assets/user-org/ddl/company",
        "out_dir": REPO_ROOT / "assets/user-org/ddl/company-verify",
        "files": None,  # glob *.sql
    },
    {
        "label": "assets/model-catalog",
        "src_dir": REPO_ROOT / "assets/model-catalog/ddl/company",
        "out_dir": REPO_ROOT / "assets/model-catalog/ddl/company-verify",
        "files": None,  # glob *.sql
    },
]


def _module_files(module):
    if module["files"] is not None:
        return list(module["files"])
    return sorted(p.name for p in module["src_dir"].glob("*.sql"))


def transform_sql(text, *, fact, dim, mart, account):
    """①②③④ 구조 토큰 치환. COMMENT 산문 내 우연한 일치도 함께 치환되지만 무관."""
    qual_map = {"fact": fact, "gpu_data": dim, "mart": mart}
    names_alt = "|".join(re.escape(n) for n in qual_map)

    # ① 한정자 fact./gpu_data./mart. -> verify명.
    text = re.sub(
        r"\b(" + names_alt + r")\.",
        lambda m: qual_map[m.group(1)] + ".",
        text,
    )

    # ② ZK 복제 경로 /clickhouse/tables/{shard}/<db>/
    text = re.sub(
        r"(/clickhouse/tables/\{shard\}/)(" + names_alt + r")(/)",
        lambda m: m.group(1) + qual_map[m.group(2)] + m.group(3),
        text,
    )

    # ③ Distributed('gpu-monitoring', '<db>', ...) 둘째 인자
    text = re.sub(
        r"(Distributed\('gpu-monitoring',\s*')(" + names_alt + r")(',)",
        lambda m: m.group(1) + qual_map[m.group(2)] + m.group(3),
        text,
    )

    # bare CREATE DATABASE IF NOT EXISTS <db> (collectors accounts.sql의 기존 fact DB 생성문)
    text = re.sub(
        r"(CREATE DATABASE IF NOT EXISTS )(" + names_alt + r")\b",
        lambda m: m.group(1) + qual_map[m.group(2)],
        text,
    )

    # ④ GRANT의 `TO mart` -> `TO <verify 계정>`
    text = re.sub(r"\bTO mart\b", f"TO {account}", text)

    return text


def build_header(*, source_rel, fact, dim, mart, account):
    return (
        "-- =============================================================\n"
        f"-- {GENERATED_BANNER}\n"
        f"-- source: {source_rel}\n"
        f"-- params: --fact={fact} --dim={dim} --mart={mart} --account={account}\n"
        "-- =============================================================\n"
    )


def build_accounts_prepend(*, fact, dim, mart, account):
    return (
        "-- -------------------------------------------------------------\n"
        "-- 1단계 격리 검증 전용 — DB 3종 + 전용 계정 생성.\n"
        "-- 철수 시: DROP DATABASE IF EXISTS <db> ON CLUSTER 'gpu-monitoring' 3종 +\n"
        "--   DROP USER IF EXISTS " + account + " ON CLUSTER 'gpu-monitoring'\n"
        "--   (docs/operations/company-verify.md 철수 절차 참조).\n"
        "-- -------------------------------------------------------------\n"
        f"CREATE DATABASE IF NOT EXISTS {fact} ON CLUSTER 'gpu-monitoring';\n"
        f"CREATE DATABASE IF NOT EXISTS {dim} ON CLUSTER 'gpu-monitoring';\n"
        f"CREATE DATABASE IF NOT EXISTS {mart} ON CLUSTER 'gpu-monitoring';\n"
        f"CREATE USER IF NOT EXISTS {account} ON CLUSTER 'gpu-monitoring' "
        "IDENTIFIED WITH sha256_password BY 'CHANGE_ME_VERIFY';\n"
        "\n"
    )


def generate_file(src_path, *, fact, dim, mart, account):
    original = src_path.read_text()
    body = transform_sql(original, fact=fact, dim=dim, mart=mart, account=account)
    source_rel = src_path.relative_to(REPO_ROOT).as_posix()
    header = build_header(source_rel=source_rel, fact=fact, dim=dim, mart=mart, account=account)
    if src_path.name == "accounts.sql":
        header += "\n" + build_accounts_prepend(fact=fact, dim=dim, mart=mart, account=account)
    else:
        header += "\n"
    return header + body


_RESIDUAL_PATTERNS = [
    re.compile(r"\b(fact|gpu_data|mart)\."),
    re.compile(r"/clickhouse/tables/\{shard\}/(fact|gpu_data|mart)/"),
    re.compile(r"Distributed\('gpu-monitoring',\s*'(fact|gpu_data|mart)',"),
    re.compile(r"CREATE DATABASE IF NOT EXISTS (fact|gpu_data|mart)\b"),
    re.compile(r"\bTO mart\b"),
]


def residual_original_tokens(text):
    """생성된 텍스트에 원 DB명 구조 토큰이 남아있는지 검사 — 남아있으면 생성기 버그.

    override 값이 원본과 동일한 이름으로 지정된 극단적 케이스는 이 검사 대상이 아니다
    (그 경우 격리 자체가 성립하지 않으므로 별개 문제)."""
    hits = []
    for pat in _RESIDUAL_PATTERNS:
        for m in pat.finditer(text):
            hits.append(m.group(0))
    return hits


def build_all(*, fact, dim, mart, account):
    """{output_path: generated_text} 딕셔너리 생성. 모듈 순회 순서 보존."""
    outputs = {}
    for module in MODULES:
        for fname in _module_files(module):
            src_path = module["src_dir"] / fname
            out_path = module["out_dir"] / fname
            outputs[out_path] = generate_file(src_path, fact=fact, dim=dim, mart=mart, account=account)
    return outputs


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--fact", default=DEFAULT_FACT, help=f"기본 {DEFAULT_FACT}")
    p.add_argument("--dim", default=DEFAULT_DIM, help=f"기본 {DEFAULT_DIM}")
    p.add_argument("--mart", default=DEFAULT_MART, help=f"기본 {DEFAULT_MART}")
    p.add_argument("--account", default=DEFAULT_ACCOUNT, help=f"기본 {DEFAULT_ACCOUNT}")
    p.add_argument("--check", action="store_true",
                    help="파일을 쓰지 않고 재생성 결과와 커밋본을 diff — 불일치 시 exit 1")
    args = p.parse_args(argv)

    outputs = build_all(fact=args.fact, dim=args.dim, mart=args.mart, account=args.account)

    # 자기 검증: 생성물 전체에 원 DB명 구조 토큰 잔존 0
    residual_errors = []
    for out_path, text in outputs.items():
        hits = residual_original_tokens(text)
        if hits:
            rel = out_path.relative_to(REPO_ROOT).as_posix()
            residual_errors.append(f"[BUG] {rel}: 원 DB명 구조 토큰 잔존 {hits}")
    if residual_errors:
        for line in residual_errors:
            print(line, file=sys.stderr)
        print("[ERROR] 생성기 자체 결함 — 치환 규칙이 누락된 구조 토큰이 있습니다.", file=sys.stderr)
        return 1

    if args.check:
        mismatches = []
        for out_path, expected in outputs.items():
            rel = out_path.relative_to(REPO_ROOT).as_posix()
            if not out_path.exists():
                mismatches.append(rel)
                print(f"[MISSING] {rel}", file=sys.stderr)
                continue
            actual = out_path.read_text()
            if actual != expected:
                mismatches.append(rel)
                print(f"[DRIFT] {rel}", file=sys.stderr)
                diff = difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=f"committed/{rel}", tofile=f"regenerated/{rel}",
                )
                sys.stderr.writelines(diff)
        if mismatches:
            print(f"[ERROR] --check: {len(mismatches)}개 파일이 커밋본과 불일치 — "
                  f"python3 tools/gen_verify_ddl.py 재실행 후 커밋하세요.", file=sys.stderr)
            return 1
        print(f"[OK] --check: {len(outputs)}개 파일 전부 커밋본과 일치")
        return 0

    for out_path, text in outputs.items():
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text)
        print(f"[WRITE] {out_path.relative_to(REPO_ROOT).as_posix()}")
    print(f"[OK] {len(outputs)}개 파일 생성 완료 (fact={args.fact} dim={args.dim} "
          f"mart={args.mart} account={args.account})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
