#!/usr/bin/env python3
"""company DDL → stage DDL 생성기.

stage(홈랩) CHI 'gpu-monitoring'은 1샤드×1레플리카에 **ZooKeeper/Keeper가 없다**
(2026-07-15 실사 — Plan 5 실배포에서 확인). 따라서 ReplicatedMergeTree와
ON CLUSTER DDL이 불가능하다. 이 생성기는 company 정본에서:

  1. `ON CLUSTER 'gpu-monitoring'` 제거 (모든 형태 — 라인/인라인/GRANT 정규형)
  2. `ENGINE = ReplicatedMergeTree(zk경로, 레플리카)` → `ENGINE = MergeTree`
  3. Distributed(...)는 유지 — 클러스터 정의는 CHI가 생성하므로 ZK 불요

를 기계 적용해 각 모듈의 ddl/stage/ 를 생성한다. company 정본이 바뀌면
재생성해야 하며 --check 가 드리프트를 잡는다 (gen_verify_ddl.py와 동일 관행).

사용:
  python3 tools/gen_stage_ddl.py            # 생성(덮어쓰기)
  python3 tools/gen_stage_ddl.py --check    # 커밋본과 대조 (CI 드리프트 가드)
"""
import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]

SOURCES = [
    "collectors/token-usage/ddl/company/raw_token_usage.sql",
    "collectors/token-usage/ddl/company/dim_token_service.sql",
    "collectors/token-usage/ddl/company/accounts.sql",
    "mart/token-usage/ddl/company/mart_tables.sql",
    "mart/token-usage/ddl/company/view_token_usage.sql",
    "mart/token-usage/ddl/company/accounts.sql",
    "assets/user-org/ddl/company/dim_token_user_org.sql",
    "assets/user-org/ddl/company/accounts.sql",
    "assets/model-catalog/ddl/company/dim_token_model.sql",
    "assets/model-catalog/ddl/company/seed_dim_token_model.sql",
    "assets/model-catalog/ddl/company/accounts.sql",
    # Plan 6a (설계 2026-08-31 §4.0 매니페스트) — collectors/mart token-metrics + 메트릭 기준정보 dim 4·시드 4·GRANT 사본
    "collectors/token-metrics/ddl/company/raw_token_metrics.sql",
    "collectors/token-metrics/ddl/company/dim_token_metrics_service.sql",
    "collectors/token-metrics/ddl/company/accounts.sql",
    "mart/token-metrics/ddl/company/mart_metrics_tables.sql",
    "mart/token-metrics/ddl/company/accounts.sql",
    "assets/model-catalog/ddl/company/dim_token_model_alias.sql",
    "assets/model-catalog/ddl/company/dim_token_gpu_tco.sql",
    "assets/model-catalog/ddl/company/dim_token_gpu_allocation.sql",
    "assets/model-catalog/ddl/company/dim_token_vendor_price.sql",
    "assets/model-catalog/ddl/company/seed_dim_token_model_alias.sql",
    "assets/model-catalog/ddl/company/seed_dim_token_gpu_tco.sql",
    "assets/model-catalog/ddl/company/seed_dim_token_gpu_allocation.sql",
    "assets/model-catalog/ddl/company/seed_dim_token_vendor_price.sql",
    "assets/model-catalog/ddl/company/accounts_metrics.sql",
]

HEADER = (
    "-- GENERATED by tools/gen_stage_ddl.py — 직접 수정 금지 (재생성으로만 갱신)\n"
    "-- stage 변형: ON CLUSTER 제거 + Replicated→MergeTree (홈랩 CHI는 ZK 없음)\n"
    "-- 원본: {src}\n\n"
)


# stage 한정 DB 부트스트랩 — 홈랩에는 동료 스택이 없어 gpu_data/mart DB도 우리가
# 생성한다 (company에서는 동료 소유라 생성 금지 — company 정본에는 없음, 실사 2026-07-15)
STAGE_DB_PREPEND = {
    "collectors/token-usage/ddl/company/accounts.sql":
        "-- stage 한정: gpu_data DB 생성 (홈랩엔 동료 스택 부재 — company에선 생성 금지)\n"
        "CREATE DATABASE IF NOT EXISTS gpu_data;\n\n",
    "mart/token-usage/ddl/company/accounts.sql":
        "-- stage 한정: mart DB 생성 (홈랩엔 동료 스택 부재 — company에선 §9-18 공유 DB)\n"
        "CREATE DATABASE IF NOT EXISTS mart;\n\n",
}


def transform(sql: str) -> str:
    # 1) ON CLUSTER — GRANT 정규형(GRANT ON CLUSTER '...' <priv>) 먼저,
    #    그다음 라인 단독/인라인 잔여 전부
    sql = sql.replace("GRANT ON CLUSTER 'gpu-monitoring' ", "GRANT ")
    sql = sql.replace("\nON CLUSTER 'gpu-monitoring'", "")
    sql = sql.replace(" ON CLUSTER 'gpu-monitoring'", "")
    # 2) ReplicatedMergeTree(zk, replica) → MergeTree (E2E 검증 규칙과 동일)
    sql = re.sub(r"ENGINE = ReplicatedMergeTree\([^)]*\)", "ENGINE = MergeTree", sql, flags=re.S)
    return sql


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    drift = []
    for rel in SOURCES:
        src = REPO / rel
        out = REPO / rel.replace("/company/", "/stage/")
        body = STAGE_DB_PREPEND.get(rel, "") + transform(src.read_text())
        rendered = HEADER.format(src=rel) + body
        # 자기 검증: 변환 잔존 0 — 주석(`--`) 제외 실코드 라인만 검사
        code_lines = [l for l in body.splitlines() if not l.lstrip().startswith("--")]
        if any("ON CLUSTER" in l or "ReplicatedMergeTree" in l for l in code_lines):
            print(f"[ERROR] 변환 잔존: {rel}", file=sys.stderr)
            return 1
        if args.check:
            if not out.exists() or out.read_text() != rendered:
                drift.append(str(out.relative_to(REPO)))
        else:
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(rendered)
            print(f"wrote {out.relative_to(REPO)}")

    if args.check:
        if drift:
            print("[DRIFT] 재생성 필요:", *drift, sep="\n  ", file=sys.stderr)
            return 1
        print(f"--check OK: {len(SOURCES)}개 파일 전부 커밋본과 일치")
    return 0


if __name__ == "__main__":
    sys.exit(main())
